// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"yet-another-media-server/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/library",
				Handler: createLibraryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/library/:library_id/scan",
				Handler: scanLibraryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/library/:library_id/media/search",
				Handler: paginateMediaByMetadataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/library/:library_id/media/:media_id",
				Handler: getMediaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/library/:library_id/metadata/:type",
				Handler: paginateMetadataHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/library/:library_id/metadata/:metadata_id",
				Handler: deleteMetadataHandler(serverCtx),
			},
		},
	)
}
