// Code generated by goctl. DO NOT EDIT.
package types

type Library struct {
	ID        int32  `json:"id"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	Name      string `json:"name"`
	BasePath  string `json:"base_path"`
}

type Media struct {
	ID        int32                  `json:"id"`
	CreatedAt int64                  `json:"created_at"`
	UpdatedAt int64                  `json:"updated_at"`
	Metadatas map[string][]*Metadata `json:"metadatas"`
	Files     []*File                `json:"files"`
}

type Metadata struct {
	ID        int32                  `json:"id"`
	CreatedAt int64                  `json:"created_at"`
	UpdatedAt int64                  `json:"updated_at"`
	Type      string                 `json:"type"`
	Value     string                 `json:"value"`
	Children  map[string][]*Metadata `json:"children"`
}

type File struct {
	ID        int32              `json:"id"`
	CreatedAt int64              `json:"created_at"`
	UpdatedAt int64              `json:"updated_at"`
	Type      string             `json:"type"`
	FilePath  string             `json:"file_path"`
	Ext       map[string]string  `json:"ext"`
	Children  map[string][]*File `json:"children"`
}

type PaginationOptions struct {
	Size int32 `form:"size,default=20"`
	Page int32 `form:"page,default=1"`
}

type PaginationResponse struct {
	Total int64         `json:"total"`
	List  []interface{} `json:"list"`
}

type CreateLibraryRequest struct {
	Name     string `json:"name"`
	BasePath string `json:"base_path"`
}

type ScanLibraryRequest struct {
	LibraryID int32             `path:"library_id"`
	Options   map[string]string `json:"options"`
}

type ScanLibraryResponse struct {
}

type Filter struct {
	Type     string `json:"type"`
	Value    string `json:"value,optional"`
	Operator string `json:"operator,default=eq"`
}

type PaginateMediaByMetadataRequest struct {
	PaginationOptions
	LibraryID int32    `path:"library_id"`
	Filters   []Filter `json:"filters"`
}

type GetMediaRequest struct {
	LibraryID int32 `path:"library_id"`
	MediaID   int32 `path:"media_id"`
}

type PaginateMetadataRequest struct {
	PaginationOptions
	LibraryID int32  `path:"library_id"`
	Type      string `path:"type"`
}

type DeleteMetadataRequest struct {
	LibraryID  int32 `path:"library_id"`
	MetadataID int32 `path:"metadata_id"`
}

type DeleteMetadataResponse struct {
}
