// Code generated by goctl. DO NOT EDIT.
// Source: scanner.proto

package server

import (
	"context"

	"yet-another-media-server/scanner/internal/logic"
	"yet-another-media-server/scanner/internal/svc"
	"yet-another-media-server/scanner/scanner"
)

type ScannerServer struct {
	svcCtx *svc.ServiceContext
	scanner.UnimplementedScannerServer
}

func NewScannerServer(svcCtx *svc.ServiceContext) *ScannerServer {
	return &ScannerServer{
		svcCtx: svcCtx,
	}
}

func (s *ScannerServer) ScanLibrary(ctx context.Context, in *scanner.ScanLibraryRequest) (*scanner.ScanLibraryResponse, error) {
	l := logic.NewScanLibraryLogic(ctx, s.svcCtx)
	return l.ScanLibrary(in)
}
